(executable
 (name merlin_worker)
 (modules merlin_worker)
 (promote (until-clean))
 (modes js wasm)
 (preprocess
  (pps js_of_ocaml-ppx))
 (libraries worker js_of_ocaml))

(executable
 (name merlin_lsp_worker)
 (modules merlin_lsp_worker)
 (promote (until-clean))
 (modes js wasm)
 (preprocess
  (pps js_of_ocaml-ppx))
 (libraries merlin_lsp js_of_ocaml))

(alias
 (name all-js)
 (deps
  merlin_worker.bc.js
  merlin_worker.bc.wasm.js
  merlin_lsp_worker.bc.js
  merlin_lsp_worker.bc.wasm.js))
